#!/usr/bin/env python3

import cv2
import numpy as np
import time
import os
import math
import sys
import gi
from datetime import datetime, timedelta
from multiprocessing import *
import subprocess
import copy

if __name__ == "__main__":
	for file in os.listdir("testtttt"):
		os.system("rm -f /home/nvidia/Bachelor/testtttt/" + file)