#!/usr/bin/env python3

from multiprocessing import *

def getSettings():
	f = open("/home/nvidia/Bachelor/config.txt", "r")
	
	currentLine = 0
	for line in f:
		#settings[currentLine] = line.strip("\n")
		settings.append(line.strip("\n"))
		currentLine += 1
	
	print(settings[0])

def annen():
	print(settings[4])
	
if __name__ == "__main__":
	m = Manager()
	settings = m.list()
	
	settingsProcess = Process(target=getSettings)
	annenProcess = Process(target=annen)
	settingsProcess.start()
	annenProcess.start()
	settingsProcess.join()
	annenProcess.join()