#!/usr/bin/env python3

import cv2
import numpy as np
import time
import os
import math
import sys
import gi
from datetime import datetime, timedelta
from multiprocessing import *
import subprocess
import copy

def read():
	videoName = "19-03-2018_10-51-30"
	#videoName = "19-03-2018_12-05-50"
	datetime_object = datetime.strptime(videoName, "%d-%m-%Y_%H-%M-%S")
	
	capture = cv2.VideoCapture("../Videoer/" + str(videoName) + ".mp4")
	#fourcc = cv2.VideoWriter_fourcc(*'X264')
	out = cv2.VideoWriter("../Videoer/ferdig.mp4", 0x00000021, 30.0, (1024,768))
	
	count = 0
	while(capture.isOpened()):
		ret, frame = capture.read()
		
		if ret == False:
			break
		
		timeOverlay = datetime_object + timedelta(seconds=count / 30)
		
		cv2.putText(frame, timeOverlay.strftime("%d/%m/%Y %H:%M:%S"), (2,762), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0,0,0), 2)
		cv2.putText(frame, timeOverlay.strftime("%d/%m/%Y %H:%M:%S"), (2,762), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (255,255,255))
		
		out.write(frame)
			
		count += 1
		
	capture.release()
	out.release()
	cv2.destroyAllWindows()

if __name__ == "__main__":
	m = Manager()
	
	while(True):
		readProcess = Process(target=read)
		
		readProcess.start()
		readProcess.join()
		
		readProcess.terminate()
		
		time.sleep(10)