#!/usr/bin/env python3

import cv2
import numpy as np

capture = cv2.VideoCapture("vid.mp4")

fourcc = cv2.VideoWriter_fourcc(*'BYR1')
out = cv2.VideoWriter("output.mp4", fourcc, 30.0, (1024,768))

startFrame = 30
endFrame = 60

count = 0
while(capture.isOpened()):
	ret, frame = capture.read()
	
	if ret == False:
		break
	
	if(count >= startFrame and count <= endFrame):
		out.write(frame)
		
	count += 1
	
capture.release()
out.release()
cv2.destroyAllWindows()
