#!/usr/bin/env python3

from paramiko import SSHClient
from scp import SCPClient

ssh = SSHClient()
ssh.load_system_host_keys()
ssh.connect("hessdalen.hiof.no")

scp = SCPClient(ssh.get_transport())

scp.put("test123.txt", "test2.txt")

scp.close()